### ISSUE TITLE
[HELP] Simple hello world example

### ISSUE THREAD

**Issue by aidv** [mikaelpatel/Arduino-OWI#12]
I've had a go with this library for a few days now and I've almost scratched a hole in my skull because I can't get it to work.

Can someone create a simple hello world example where two Arduinos send two bytes to each other?

Or maybe they could send a string where Arduino A sends "hello" and Arduino B replies with "world"?

Please, Thanks.

**Comment by mikaelpatel** [comment]
Please see the exemples library.
