### ISSUE TITLE
Improve addressing of slave devices

### ISSUE THREAD

**Issue by mikaelpatel** [mikaelpatel/Arduino-OWI#5]
When using devices on the same bus addressing is either by MATCH_ROM(64b) or SEARCH_ROM(3*64b). This requires a lot of addressing bits on an already slow channel. 

With software slave devices it is possible to introduce a short address, i.e. label. This would require some new ROM function; LABEL_ROM(8b) and MATCH_LABEL(8b). SEARCH_ROM could be used to iterate the devices and use LABEL_ROM(nr) to set sequence number. MATCH_ROM(nr) is then used instead of MATCH_ROM(nr). This reduces the address from 64b to 8b.

**Comment by hattesen** [comment]
Is the use of 8-bit labels part of any (Maxim) recommendation/standard, or is it a custom-extension?

The only reference to LABELing 1-Wire devices, that I can find, is the [APPLICATION NOTE 158 |  
1-Wire Tagging with XML](https://www.maximintegrated.com/en/app-notes/index.mvp/id/158), but that is implemented as a separate XML file, containing information about (slave) devices, and is indexed on the full 64 bit ROM address.

The two proposals (LABEL_ROM()/MATCH_LABEL() and XML-tagging)  would work great in conjunction, provided the XML schema would allow each entry to hold an (8-bit) LABEL reference, e.g.:

`<parentElement addr="77000000023CEC12">
    <label id="3F">(textual label)</label>
    ...
</parentElement>`

... where `parentElement` is one of: `branch`, `sensor`, `actuator`.

But that would require a change (extension) of the current XML Tagging standard/spec.

**Comment by mikaelpatel** [comment]
> Is the use of 8-bit labels part of any (Maxim) recommendation/standard, or is it a custom-extension?

No, my "invention" to reduce addressing of slave devices written with this library. It is not part of any standard and there are no commercial devices that support it. 

Any this "feature" is already implement. Forgot to close the issue. Sorry about that.
